package JSON.EnumsAndParameters;

/**
 * enum holding all requestable attributes, to see which ones match which machine, see config for statusRequests
 */
public enum RequestedParameter {

    //Warehouse:
    REFERENCESWITCHHORIZONTALAXIS,
    LIGHTBARRIERINSIDE,
    LIGHTBARRIEROUTSIDE,
    REFERENCESWITCHVERTICALAXIS,
    HORIZONTALAXISSTEP,
    VERTICALAXISSTEP,
    REFERENCESWITCHCANTILEVERFRONT,
    REFERENCESWITCHCANTILEVERBACK,
    MOTORCONVEYORBELTFORWARD,
    MOTORCONVEYORBELTBACKWARD,
    MOTORVERTICALAXISDOWNWARD,
    MOTORVERTICALAXISUPWARD,
    MOTORCANTILEVERFORWARD,
    MOTORCANTILEVERBACKWARD,

    //Indexed line:
    PUSHBUTTONSLIDER1FRONT,
    PUSHBUTTONSLIDER1REAR,
    PUSHBUTTONSLIDER2FRONT,
    PUSHBUTTONSLIDER2REAR,
    LIGHTBARRIERSLIDER1,
    LIGHTBARRIERMILLINGMACHINE,
    LIGHTBARRIERLOADINGSTATION,
    LIGHTBARRIERDRILLINGMACHINE,
    LIGHTBARRIERCONVEYORBELTSWAP,
    MOTORSLIDER1BACKWARD,
    MOTORSLIDER1FORWARD,
    MOTORSLIDER2BACKWARD,
    MOTORSLIDER2FORWARD,
    MOTORCONVEYORBELTFEED,
    MOTORCONVEYORBELTMILLINGMACHINE,
    MOTORMILLINGMACHINE,
    MOTORCONVEYORBELTDRILLINGMACHINE,
    MOTORDRILLINGMACHINE,
    MOTORCONVEYORBELTSWAP,

    //Multiprocessing:
    REFERENCESWITCHTURNTABLEPOSITIONVACUUM,
    REFERENCESWITCHTURNTABLEPOSITIONBELT,
    LIGHTBARRIERENDOFCONVEYORBELT,
    REFERENCESWITCHTURNTABLEPOSITIONSAW,
    REFERENCESWITCHVACUUMPOSITIONTURNTABLE,
    REFERENCESWITCHOVENFEEDERINSIDE,
    REFERENCESWITCHOVENFEEDEROUTSIDE,
    REFERENCESWITCHVACUUMPOSITIONOVEN,
    LIGHTBARRIEROVEN,
    MOTORTURNTABLECLOCKWISE,
    MOTORTURNTABLECOUNTERCLOCKWISE,
    MOTORSAW,
    MOTOROVENFEEDERRETRACT,
    MOTOROVENFEEDEREXTEND,
    MOTORVACUUMTOWARDSOVEN,
    MOTORVACUUMTOWARDSTURNTABLE,
    LIGHTOVEN,
    VALVEVACUUM,
    VALVELOWERING,
    VALVEOVENDOOR,
    VALVEFEEDER,

    //Sorting line:
    PULSECOUNTER,
    LIGHTBARRIERINLET,
    LIGHTBARRIERBEHINDCOLORSENSOR,
    LIGHTBARRIERWHITE,
    LIGHTBARRIERRED,
    LIGHTBARRIERBLUE,
    MOTORCONVEYORBELT,
    COMPRESSOR,
    VALVEFIRSTEJECTORWHITE,
    VALVESECONDEJECTORRED,
    VALVETHIRDEJECTORBLUE,

    //Vacuum gripper:
    REFERENCESWITCHROTATE,
    ROTATESTEP,
    MOTORVERTICALAXISUP,
    MOTORVERTICALAXISDOWN,
    MOTORHORIZONTALAXISBACKWARD,
    MOTORHORIZONTALAXISFORWARD,
    MOTORROTATECLOCKWISE,
    MOTORROTATECOUNTERCLOCKWISE,

    //Conveyor:
    LIGHTBARRIERFEEDSTATION,
    LIGHTBARRIERSWAPSTATION,

    //Punching machine:
    LIGHTBARRIERGOODSINOUT,
    LIGHTBARRIERPUNCHINGMACHINE,
    SWITCHPUNCHINGMACHINEUP,
    SWITCHPUNCHINGMACHINEDOWN,
    MOTORPUNCHINGMACHINEUP,
    MOTORPUNCHINGMACHINEDOWN,

    //3dRobot:
    REFERNCESWITCHCLAW,
    PULSECOUNTERGRIPPER,
    REFERENCESWITCHGRIPARM,
    PULSECOUNTERGRIPARM,
    MOTORGRIPPEROPEN,
    MOTORGRIPPERCLOSE,
    MOTORGRIPARMFORWARD,
    MOTORGRIPARMBACKWARD,

    ALL //DS Request
}
