services:
    mosquitto:
        image: eclipse-mosquitto:2
        container_name: mqtt-broker
        user: 1000:1000
        ports:
            - 1883:1883
        volumes:
            - ./config:/mosquitto/config
            - ./data:/mosquitto/data
            - /var/log/mosquitto:/mosquitto/log
        restart: unless-stopped
