
# Configuration for VacuumGripperController
---
plc:
  id: "RevPi01"
connection:
  # if host is commented, will default to "<hostname>.local"
  # host: "localhost"
  host: "RevPi103156.local"
  command_port: 6001
  notification_port: 6011
  # connectionListening: "controller" or "orchestrator"
  connectionListening: "controller"

controller:
  mainLoopDelay: 0.15

mqtt:
  server: "mbdo-server.local"
  port: 1883
  keepalive: 60