<!-- The gateway_request.xsd is used to validate the gateway_request.xml -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://isw.unistuttgart.de/dts/gateway"
           xmlns:tns="http://isw.unistuttgart.de/dts/gateway" 
           elementFormDefault="qualified">

    <xs:complexType name="t_replyTo">
        <xs:sequence>
            <xs:element name="target">
                <xs:complexType>
                    <xs:choice>                    
                        <xs:element name="rabbitmq">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="queueName" type="xs:string"/>
                                    <xs:element name="exchangeName" type="xs:string"/>
                                    <xs:element name="routingKey" type="xs:string"/>
                                    <xs:element name="brokerID" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="rest">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="path" type="xs:string"/>
                                    <xs:element name="method">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="GET"/>
                                                <xs:enumeration value="POST"/>
                                                <xs:enumeration value="PUT"/>
                                                <xs:enumeration value="DELETE"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="correlationID" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="t_request">
        <xs:sequence>
            <xs:element name="endpoint">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="service" type="xs:string"/>
                        <xs:element name="path" type="xs:string"/>
                        <xs:element name="method">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="GET"/>
                                    <xs:enumeration value="POST"/>
                                    <xs:enumeration value="PUT"/>
                                    <xs:enumeration value="DELETE"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="body">
               <xs:complexType>
                    <xs:sequence>
                        <xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="type" type="xs:string"/>
                                         <xs:attribute name="key" type="xs:string"/>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="t_gatewayRequest">
        <xs:sequence>
            <xs:element name="replyTo" type="tns:t_replyTo" />
            <xs:element name="request" type="tns:t_request" />
        </xs:sequence>
    </xs:complexType>


    <xs:element name="gatewayRequest" type="tns:t_gatewayRequest" />
</xs:schema>
