This folder contains a virtual setup  for a mini factory composed of a Converyor Belt, a Sorting Line, a MultiProcessingMachine, a HighBayWarehouse, and a Vacuum Gripper Robot (VGR).

This allows testing the controller, SCADA Digital Twin tooling without access to the physical Fishertechnik machines.


== Quick start

===  Install and run a mqtt broker

an easy way to get a mqtt broker running on you machine:

go to `VIRTUAL_Setups/VIRTUAL_shared/mosquito` and run 

[source,shell]
----
docker compose up
----

=== Activate your python environment

NOTE: you must make sure to have added the folder containing the rppmcontroller code in development mode in the python environment (see https://git.rwth-aachen.de/mbdo/mbdo-impl/-/blob/master/rppmcontroller/README.md?ref_type=heads#install-the-development-environment)

if  you use the conda environment:

[source,shell]
----
conda activate rppmcontroller
----


=== Start simulated machine controller

[source,shell]
----
cd config/PLC1
----

[source,shell]
----
python3 SimulatedMachines_Controller.py.py
----

=== Start SCADA in dev mode for this setup

Frontend
[source,shell]
----
cd ../../factoryscada/frontend
----

[source,shell]
----
npm run start
----

Backend
[source,shell]
----
cd ../../factoryscada/backend
----

[source,shell]
----
./gradlew bootrun --args='--missions.parallelized.configuration.path=../../VIRTUAL_Setups/VIRTUAL_1C1H1M1S1V_01/config/server/factoryscada/services/scada-backend/config/missions-parallelized-configuration.yml --configuration.path=../../VIRTUAL_Setups/VIRTUAL_1C1H1M1S1V_01/config/server/factoryscada/services/scada-backend/config/configuration.yml'
----



=== Note about machines speed

For calibrating  the simulatedMachines speed with respect to the cycle step time, the following where used as reference:

- Cycle step set to 0.1s
- VGR: process 1000 (horizontal, vertical or rotation ) in about 3 seconds : increment of 33 per cycle step
- CB: count about 20 steps in about 3 seconds : increment of 1 per cycle step


