@startuml

component "Weather Service" as weather_service

component "Construction Forecast Service" as construction_forecast_service

component "Vehicle Maintaince Service" as vehicle_maintaince_service

component "Energy Consumption Service" as energy_consumption_service

component "Energy Provider Service" as energy_provider_service

component "Wind Energy Forecast Service" as wind_energy_forecast_service


wind_energy_forecast_service --> weather_service: "depends on"
construction_forecast_service --> weather_service: "depends on"
vehicle_maintaince_service --> construction_forecast_service: "depends on"
energy_consumption_service --> construction_forecast_service: "depends on"
energy_provider_service --> energy_consumption_service: "depends on"
energy_consumption_service --> energy_provider_service: "depends on"
energy_provider_service --> wind_energy_forecast_service: "depends on"
@enduml