@startuml
class "Coordinates" as Coordinates {
    + latitude: Double
    + longitude: Double
}

class "Humidity" as Humidity {
    + value: Double
    + unit: String
}

class "Precipitation" as Precipitation {
    + amount: Double
    + unit: String
}

class "Temperature" as Temperature {
    + value: Double
    + unit: String
}

class "WeatherData" as WeatherData {
    + coordinates: Coordinates
    + temperature: Temperature
    + wind: Wind
    + humidity: Humidity
    + precipitation: Precipitation
}

class "RequestWeatherData" as RequestWeatherData {
}

class "Wind" as Wind {
    + speed: Double
    + direction: String
    + speedUnit: String
}

class "WeatherService" as weatherService {
}


@enduml
