- name: Pull revpi config to rppmcontroller_current_setup folder
  ansible.builtin.synchronize:
    #src: "{{ python_config_folder_path }}"
    src: /var/www/revpi/pictory/projects/_config.rsc
    dest: ../../config/{{ inventory_hostname }}/PiCtory/_config.rsc
    mode: pull
    use_ssh_args: yes # required to enable jump ansible_host
    recursive: false
    delete: false  # 'true' to delete files not in the source

- name: Pretty-print pulled .rsc JSON file locally
  ansible.builtin.shell: >
    python3 -m json.tool ../../config/{{ inventory_hostname }}/PiCtory/_config.rsc
    > ../../config/{{ inventory_hostname }}/PiCtory/tmp/_config.rsc
    && mv ../../config/{{ inventory_hostname }}/PiCtory/tmp/_config.rsc
    ../../config/{{ inventory_hostname }}/PiCtory/_config.rsc
  delegate_to: localhost
  args:
    executable: /bin/bash