@startuml
!pragma layout smetana
left to right direction

interface IBootable {
    + void start()
    + void setConfig(Config config)
}
interface IPermissionRestricted {
    + List<ServicePermission> getAllPermissions();
}
interface GatewayInboundConnection {
 
    ' This method is called when a message is received
    + void onMessage(String input)

    ' This method is called when a message is parsed
    + void onParsedMessage(TServiceRequest serviceRequest)

}
interface GatewayOutboundConnection {
    + void sendMessage(TGatewayRequest message)
}

package Query {
    interface Callable {
        + void onCall(CallOperation operation)
    }
    interface Deletable {
        + void onDelete(DeleteOperation operation)
    }
    interface Updateable {
        + void onUpdate(UpdateOperation operation)
    }
    interface Selectable {
        + void onSelect(SelectOperation operation)
    }
}

interface Renderable{
    + void render(RenderOperation operation)
}



abstract class CrudService {
    - Config config
    - ServiceMailbox<TServiceRequest, ObjectFactory> mailbox

    + String mailboxName()
}

abstract class UiService {
    - Config config
    - ServiceMailbox<TServiceRequest, ObjectFactory> mailbox
    + String mailboxName()
}

abstract class ComputationService {
    - Config config
    - ServiceMailbox<TServiceRequest, ObjectFactory> mailbox
    + String mailboxName()
}

CrudService .|> IBootable
CrudService .|> IPermissionRestricted
CrudService ..|> GatewayInboundConnection
CrudService .|> GatewayOutboundConnection 
 
ComputationService .|> IBootable
ComputationService .|> IPermissionRestricted  
ComputationService ..|> GatewayInboundConnection
ComputationService .|> GatewayOutboundConnection 

  
CrudService ..|> Callable
CrudService ..|> Deletable
CrudService ..|> Updateable
CrudService ..|> Selectable
 
ComputationService ..|> Callable

UiService .|> IBootable
UiService .|> IPermissionRestricted
UiService ..|> GatewayInboundConnection
UiService .|> GatewayOutboundConnection
UiService ..|> Renderable


@enduml
