class GatewayRequest {
    dsl: GatewayDSL;
    responseTarget: GatewayRequestResponse
}

interface GatewayRequestResponse<T> {

    + getResponse(): T;
    + getTypeName(): string;    
  
}

class ServiceRequest {

}

class Gateway {

}

class ComputationService {

}

class VisualizationService {

}

class GatewayDSL {
    List<GatewayDSLStatement> components;
}

interface GatewayDSLComponent {

}

class GatewayDSLStatement implements GatewayDSLComponent{

}

class GatewayDSLOperator implements GatewayDSLComponent{

    firstStmt: GatewayDSLStatement;
    secondStmt: GatewayDSLStatement;
    operatorValue: DSLOPERATOR
}

enum DSLOPERATOR {
    JOIN,
    UNION,
    INTERSECTION,
    GROUP,
    DESCRIBE,
    SELECT,
    SELECT_WHERE,
}