@startuml

component "ServiceGateway" {
    component "ServiceEngine" as service_engine {
        component "DSL Engine" as dsl_engine     
        component "ServiceRegistry" as service_registry {
        }
        component "EventRegistry" as event_registry {
        }
        component "AuthHandler" as auth_handler {
        }
        dsl_engine --> event_registry: "Fetch/Push events"
    }
    
    component "RestAPI" as rest_api {
    }
    component "WebSocketAPI" as websocket_api {
    }

    dsl_engine -> service_registry: Fetch services from registry
    dsl_engine --> auth_handler: runs authentication checks

    rest_api --> service_engine: REST API calls and forwards to service engine
    websocket_api --> service_engine: Websocket API calls and forwards to service engine
}

@enduml