
configuration:
  mqtt:
    inbound:
      host: tcp://mbdo-server.local:1883
      topics: "#"
    outbound:
      host: tcp://mbdo-server.local:1883
      root-topic: "FactorySCADABackend"
      topic-include-hostname: True
