# Configuration (00)

configuration:
  name: "REN_1S1V_1C1V_1H1M_02_configuration"
  mqttHost: "tcp://mbdo-server.local:1883"

  controllers:
    - name: "plc-1"
      host: 'RevPi103156.local'
      commandPort: 6001
      notificationPort: 6011
      machines:
        - type: "sortingLine"
          name: "I1SortingLine01"

        - type: "vacuumGripper"
          name: "I1VacuumGripper01"

    - name: "plc-2"
      host: 'RevPi103259.local'
      commandPort: 6001
      notificationPort: 6011
      machines:
        - type: "conveyorBelt"
          name: "I1ConveyorBelt01"

        - type: "vacuumGripper"
          name: "I1VacuumGripper02"

    - name: "plc-3"
      host: 'RevPi103228.local'
      commandPort: 6001
      notificationPort: 6011
      machines:
        - type: "multiProcessingStation"
          name: "I1MultiProcessing01"

        - type: "highBayWarehouse"
          name: "I1HighBay01"   

  machineNameMappings:
    - logicalName: "DynamicMission/Demo/SL"
      machineName: "I1SortingLine01"
    - logicalName: "DynamicMission/Demo/VGR2"
      machineName: "I1VacuumGripper01"
    - logicalName: "DynamicMission/Demo/CB"
      machineName: "I1ConveyorBelt01"
    - logicalName: "DynamicMission/Demo/VGR1"
      machineName: "I1VacuumGripper02"
    - logicalName: "DynamicMission/Demo/MPS"
      machineName: "I1MultiProcessing01"
    ###

    - logicalName: "REN_MISSION_01/SL01"
      machineName: "I1SortingLine01"
    - logicalName: "REN_MISSION_01/VGR02"
      machineName: "I1VacuumGripper02"
    - logicalName: "REN_MISSION_01/CB01"
      machineName: "I1ConveyorBelt01"
    - logicalName: "REN_MISSION_01/VGR01"
      machineName: "I1VacuumGripper01"
    - logicalName: "REN_MISSION_01/MPS01"
      machineName: "I1MultiProcessing01"