factoryMissionsConfiguration:
  name: "Factory missions"
  missions:
    - name: "VGR1/CB1 mini mission"
      description: >
        Mission involving VacuumGripper01 and ConveyorBelt01.
        The VGR picks a token on the left side of the Conveyor and places it on the right side of the Conveyor.
        Then the conveyor moves back the token to its left side.  
      commands:
      - name: "VGR1_Pick"
        description: "[VGR1] Pick on left of CB1"
        placeholder: >
          {
            "topicName": "VacuumGripper01",
            "timestamp": 0,
            "message": {
              "jsonType": "COMMAND",
              "type": "VACUUM",
              "outputId": "AUTO_ID",
              "name": "PICK",
              "parameters": [
                {
                  "passableType": "POSITIONPARAMETERTHREED",
                  "passable": {
                    "meaning": "START",
                    "vertical": 1450,
                    "horizontal": 1480,
                    "rot": 1920
                  }
                }
              ]
            }
          }
      - name: "VGR1_Place"
        description: "[VGR1] Place on right of CB1"
        placeholder: >
          {
            "topicName": "VacuumGripper01",
            "timestamp": 0,
            "message": {
              "jsonType": "COMMAND",
              "type": "VACUUM",
              "outputId": "AUTO_ID",
              "name": "PLACE",
              "parameters": [
                {
                  "passableType": "POSITIONPARAMETERTHREED",
                  "passable": {
                    "meaning": "START",
                    "vertical": 1450,
                    "horizontal": 1820,
                    "rot": 1530
                  }
                }
              ]
            }
          }
      - name: "CB1_Move_to_sensor"
        description: "[CB1] Move to left sensor"
        placeholder: >
          {
            "topicName" : "ConveyorBelt01",
            "timestamp" : 0,
            "message" : {
              "jsonType" : "COMMAND",
              "type" : "CONVEYOR",
              "outputId" : "AUTO_ID",
              "name": "MOVE_TO_SENSOR",
              "parameters": [
                  {
                      "passableType": "DIRECTION",
                      "passable": {
                          "direction": "BACKWARD"
                      }
                  }
              ]
            }
          }



    - name: "Sort_Process_Store_Mission"
      description: >
        Mission involving all machines.
        The sorting line sort the payload to red, then the vacuum gripper 1 take it to the conveyor.
        The conveyor move it forward and the vacuum gripper 2 take it to the multi processing station.
        Then the vacuum gripper move it to the highbay, which store it.
      commands:
      - name: "HBW_Retrieve"
        description: "[MPS1] Retrieve box from place 1;1"
        placeholder: >
          {
            "topicName": "HighBay01",
            "timestamp": 1750259441566,
            "message": {
                "jsonType": "COMMAND",
                "type": "WAREHOUSE",
                "outputId": 1,
                "name": "PICKUP_FROM",
                "parameters": [
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    },
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    }
                ]
            }
          }
      - name: "VGR2_Move"
        description: "[VGR2] Move from HBW to CB"
        placeholder: >
          {
            "topicName": "VacuumGripper02",
            "timestamp": 1750259239375,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 1,
                "name": "MOVE",
                "parameters": [
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "START",
                            "vertical": 100,
                            "horizontal": 800,
                            "rot": 1030
                        }
                    },
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "END",
                            "vertical": 1100,
                            "horizontal": 1400,
                            "rot": 2700
                        }
                    }
                ]
            }
          }
      - name: "VG2_RetractArm"
        description: "[VG2] Retract arm"
        placeholder: >
          {
            "topicName": "VacuumGripper02",
            "timestamp": 1750322931414,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 2,
                "name": "RETRACT_ARM",
                "parameters": []
            }
          }
      - name: "HBW_Store"
        description: "[MPS1] Store payload to place 1;1"
        placeholder: >
          {
            "topicName": "HighBay01",
            "timestamp": 1750259441566,
            "message": {
                "jsonType": "COMMAND",
                "type": "WAREHOUSE",
                "outputId": 1,
                "name": "STORE_TO",
                "parameters": [
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    },
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    }
                ]
            }
          }
      - name: "CB1_Move_to_sensor"
        description: "[CB1] Move to left sensor"
        placeholder: >
          {
            "topicName" : "ConveyorBelt01",
            "timestamp" : 0,
            "message" : {
              "jsonType" : "COMMAND",
              "type" : "CONVEYOR",
              "outputId" : "AUTO_ID",
              "name": "MOVE_TO_SENSOR",
              "parameters": [
                  {
                      "passableType": "DIRECTION",
                      "passable": {
                          "direction": "BACKWARD"
                      }
                  }
              ]
            }
          }
      - name: "VGR1_Move"
        description: "[VGR1] Move from SL to CB"
        placeholder: >
          {
            "topicName": "VacuumGripper01",
            "timestamp": 1750259239375,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 1,
                "name": "MOVE",
                "parameters": [
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "START",
                            "vertical": 1200,
                            "horizontal": 1440,
                            "rot": 1900
                        }
                    },
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "END",
                            "vertical": 1000,
                            "horizontal": 1590,
                            "rot": 2870
                        }
                    }
                ]
            }
          }
      - name: "SL1_Sort"
        description: "[SL1] Sort to red"
        placeholder: >
          {
            "topicName": "SortingLine01",
            "timestamp": 1750259194372,
            "message": {
                "jsonType": "COMMAND",
                "type": "SORTING",
                "outputId": 7,
                "name": "EJECT",
                "parameters": [
                    {
                        "passableType": "COLOR",
                        "passable": {
                            "color": "RED"
                        }
                    }
                ]
            }
          }
      - name: "VGR1_Move"
        description: "[VGR1] Move from SL to CB"
        placeholder: >
          {
            "topicName": "VacuumGripper01",
            "timestamp": 1750259239375,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 1,
                "name": "MOVE",
                "parameters": [
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "START",
                            "vertical": 1350,
                            "horizontal": 1300,
                            "rot": 2230
                        }
                    },
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "END",
                            "vertical": 1100,
                            "horizontal": 1390,
                            "rot": 1800
                        }
                    }
                ]
            }
          }
      - name: "VG1_RetractArm"
        description: "[VG1] Retract arm"
        placeholder: >
          {
            "topicName": "VacuumGripper01",
            "timestamp": 1750322931414,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 2,
                "name": "RETRACT_ARM",
                "parameters": []
            }
          }
      - name: "CB1_Move_to_sensor"
        description: "[CB1] Move to right sensor"
        placeholder: >
          {
            "topicName" : "ConveyorBelt01",
            "timestamp" : 0,
            "message" : {
              "jsonType" : "COMMAND",
              "type" : "CONVEYOR",
              "outputId" : "AUTO_ID",
              "name": "MOVE_TO_SENSOR",
              "parameters": [
                  {
                      "passableType": "DIRECTION",
                      "passable": {
                          "direction": "FORWARD"
                      }
                  }
              ]
            }
          }
      - name: "VGR2_Move"
        description: "[VGR2] Move from CB to MPS"
        placeholder: >
          {
            "topicName": "VacuumGripper02",
            "timestamp": 1750259239375,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 1,
                "name": "MOVE",
                "parameters": [
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "START",
                            "vertical": 1100,
                            "horizontal": 1400,
                            "rot": 2700
                        }
                    },
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "END",
                            "vertical": 800,
                            "horizontal": 1790,
                            "rot": 2025
                        }
                    }
                ]
            }
          }
      - name: "VG2_RetractArm"
        description: "[VG2] Retract arm"
        placeholder: >
          {
            "topicName": "VacuumGripper02",
            "timestamp": 1750322931414,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 2,
                "name": "RETRACT_ARM",
                "parameters": []
            }
          }
      - name: "MPS_Process1"
        description: "[MPS1] Execute process1"
        placeholder: >
          {
            "topicName": "MultiProcessing01",
            "timestamp": 1750259348009,
            "message": {
                "jsonType": "COMMAND",
                "type": "MULTIPROCESSING",
                "outputId": 1,
                "name": "PROCESS1",
                "parameters": []
            }
          }
      - name: "HBW_Retrieve"
        description: "[MPS1] Retrieve box from place 1;1"
        placeholder: >
          {
            "topicName": "HighBay01",
            "timestamp": 1750259441566,
            "message": {
                "jsonType": "COMMAND",
                "type": "WAREHOUSE",
                "outputId": 1,
                "name": "PICKUP_FROM",
                "parameters": [
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    },
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    }
                ]
            }
          }
      - name: "VGR2_Move"
        description: "[VGR2] Move from MPS to HBW"
        placeholder: >
          {
            "topicName": "VacuumGripper02",
            "timestamp": 1750259239375,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 1,
                "name": "MOVE",
                "parameters": [
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "START",
                            "vertical": 1050,
                            "horizontal": 1900,
                            "rot": 1460
                        }
                    },
                    {
                        "passableType": "POSITIONPARAMETERTHREED",
                        "passable": {
                            "meaning": "END",
                            "vertical": 0,
                            "horizontal": 800,
                            "rot": 1030
                        }
                    }
                ]
            }
          }
      - name: "VG2_RetractArm"
        description: "[VG2] Retract arm"
        placeholder: >
          {
            "topicName": "VacuumGripper02",
            "timestamp": 1750322931414,
            "message": {
                "jsonType": "COMMAND",
                "type": "VACUUM",
                "outputId": 2,
                "name": "RETRACT_ARM",
                "parameters": []
            }
          }
      - name: "HBW_Store"
        description: "[MPS1] Store payload to place 1;1"
        placeholder: >
          {
            "topicName": "HighBay01",
            "timestamp": 1750259441566,
            "message": {
                "jsonType": "COMMAND",
                "type": "WAREHOUSE",
                "outputId": 1,
                "name": "STORE_TO",
                "parameters": [
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    },
                    {
                        "passableType": "NUMBERNATURAL",
                        "passable": {
                            "number": 1
                        }
                    }
                ]
            }
          }