# Configuration (00)

configuration:
  name: "REN_1S1V_1C1V_1H1M_02_configuration"

  controllers:
    - name: "virtualmachines-plc-1"
      host: 'localhost'
      commandPort: 6001
      notificationPort: 6011
      machines:
        - type: "conveyorBelt"
          name: "ConveyorBelt01"

        - type: "highBayWarehouse"
          name: "HighBay01"   

        - type: "multiProcessingStation"
          name: "MultiProcessing01"
        
        - type: "sortingLine"
          name: "SortingLine01"

        - type: "vacuumGripper"
          name: "VacuumGripper01"

