FactoryMissionsParallelized:
  name: "Factory missions parallelized"
  missions:
    - name: "VGR setup and CB moving"
      description: >
        Setup the vacuum gripper and forward the conveyor belt a few step
      nodes:
        - type: entryNode
          id: "Entry node"
          description: >
              The entry node
          outputs: 
            - Fork1

        - type: fork
          id: "Fork1"
          description: >
            The first Fork
          outputs:
            - ActionNode1
            - WaitAction

        - type: rawMachineCommand
          id: "ActionNode1"
          description: >
            Setup the VG1
          placeholder: >
            {
              "topicName": "VacuumGripper01",
              "timestamp": 1751547231773,
              "message": 
                {
                  "jsonType": "COMMAND",
                  "type": "VACUUM",
                  "outputId": "AUTO_ID",
                  "name": "SETUP",
                  "parameters": []
                }
            }
          outputs:
            - Join1

        - type: waitAction
          id: "WaitAction"
          description: >
            Wait for 10s
          time: 10
          outputs:
            - Join1

        - type: join
          id: "Join1"
          description: >
            The last join
          outputs:
            - ActionNode3
        
        - type: rawMachineCommand
          id: "ActionNode3"
          description: >
            Move back the CB
          placeholder: >
            {
              "topicName": "ConveyorBelt01",
              "timestamp": 1751547508462,
              "message": 
                {
                  "jsonType": "COMMAND",
                  "type": "CONVEYOR",
                  "outputId": "AUTO_ID",
                  "name": "MOVE_NB_STEPS",
                  "parameters": [
                      {
                          "passableType": "NUMBERNATURAL",
                          "passable": {
                              "number": 5
                          }
                      },
                      {
                          "passableType": "DIRECTION",
                          "passable": {
                              "direction": "BACKWARD"
                          }
                      }
                  ]
                }
            }
          outputs: []



