---

## example of use:
# ansible-playbook  playbooks/push_server_config.yml 

- name: Push Server configuration
  hosts: mbdo_server
  
  tasks:
  - name: Load the variables
    include_vars: ../vars.yml
  - name: Push factoryscada directory contents
    synchronize:
      src: ../../config/server/factoryscada/
      dest: /home/mbdo-admin/mbdo/factoryscada
      recursive: true
      delete: true  # 'true' to delete files not in the source
  - name: Push gateway directory contents
    synchronize:
      src: ../../config/server/gateway/
      dest: /home/mbdo-admin/mbdo/gateway
      recursive: true
      delete: true  # 'true' to delete files not in the source