@startuml
actor "Requester" as requester
participant "Service Gateway API" as service_gateway_api
participant "Service Engine" as service_engine
participant "DSL Engine" as dsl_engine
participant "Service Registry" as service_registry
participant "Event Registry" as event_registry
participant "Auth Handler" as auth_handler
participant "Service"

requester -> service_gateway_api: Send a SGQL request
service_gateway_api -> service_engine: Handle SGQL request
service_engine -> dsl_engine: Parse SGQL request
service_engine <- dsl_engine: Parsed SGQL request
service_engine -> service_registry: Fetch services from registry
service_engine -> auth_handler: Runs authentication checks
service_engine -> event_registry: Fetch Events Details
' if script contains service then call service
alt script contains service
    service_engine -> Service: Execute Service
end
' if script contains event then call event
alt script contains event
    service_engine -> event_registry: Push/Pull Events
end

@enduml