plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.5'
	id 'io.spring.dependency-management' version '1.1.6'
	id("com.github.bjornvester.xjc") version "1.8.1"
	id "de.monticore.generator" version "$mc_version" // MontiCore Plugin
	id 'maven-publish'
}

group = 'de.uni-stuttgart.isw'
version = '0.0.1-SNAPSHOT'

def guava_version = '33.1.0-jre'
def junit_version = '5.10.3'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

sourceSets {
	main {
		java {
			srcDirs += "${buildDir}/generated/sources/xjc"
			srcDirs += "${buildDir}/generated/sources/monticore"
		}
		resources {
			srcDirs = ['src/main/resources']
		}
	}

	test {
		resources {
			 
			 srcDirs = ['src/test/resources', 'src/main/resources'] 
		}
	}
}

xjc {
    xsdDir = file('src/main/resources/xsd')
	outputJavaDir.set file("${buildDir}/generated/sources/xjc")
}


generateMCGrammars {
  // The mc4 grammars are build from the src/main/grammars directory by default
  // You do not have to configure anything, the de.monticore.generator plugin does it all
  // Reasonable defaults are used, further details: https://monticore.github.io/monticore/docs/Gradle/
  outputDir.set file("${buildDir}/generated/sources/monticore")
}


repositories {
  mavenCentral()
  maven {
    url repo
  }
}

publishing {
	 publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "localRepo"
            url = uri("${rootProject.buildDir}/repo")
        }
    }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.amqp:spring-rabbit-test'
	implementation 'io.github.classgraph:classgraph:4.8.158'
	implementation 'com.rabbitmq:amqp-client:5.22.0'
	implementation 'org.glassfish.jaxb:jaxb-runtime:3.0.2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	grammar ("de.monticore:monticore-grammar:$mc_version") {capabilities {
      requireCapability("de.monticore:monticore-grammar-grammars") }
    }
	implementation "de.monticore:monticore-runtime:${project.properties['mc_version']}"
    implementation "de.monticore:monticore-grammar:${project.properties['mc_version']}"

	// Next, dependencies of the project itself
	implementation group: 'com.google.guava', name: 'guava', version: guava_version
	implementation group: 'de.monticore.lang', name: 'cd4analysis', version: mc_version
	implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'

	// And dependencies for the test source set
	testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
	testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_version"
	// Provide MontiCore-specific tests, such as de.monticore.cocos.helper.Assert
	testImplementation "de.monticore:monticore-runtime:${project.properties['mc_version']}"

}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.named("generateMCGrammars") {
    dependsOn(":xjc")
}



tasks.register("generateServiceExport") {	
	doLast {		
		 // Set the classpath to include compiled Java classes
        def classLoader = new URLClassLoader(
            sourceSets.main.runtimeClasspath.files.collect { it.toURI().toURL() } as URL[],
            this.class.classLoader
        )
		// Load and invoke the method
		def mainClass = classLoader.loadClass("de.unistuttgart.isw.annotations.ExportGenerator")
		def instance = mainClass.getDeclaredConstructor().newInstance()
		def method = mainClass.getMethod("generateServiceExport", String.class, String.class)
		// output directory is base dir + "typeDef"
		def outputDir = new File("${project.projectDir}/typeDef")
		if (!outputDir.exists()) {
			outputDir.mkdirs()
		}
		def outputDirPath = outputDir.getAbsolutePath()
		// Set the output directory
		method.invoke(instance, "de.unistuttgart.isw", outputDirPath)
	}	
}

tasks.named("generateServiceExport") {
	dependsOn("compileJava")
}