spring.application.name=dtservices

SERVICE_TOPIC_NAME="sample_computation_service"
SERVICE_QUEUE_NAME="sample_computation_service_queue"
GATEWAY_QUEUE_NAME="gateway_queue"
SERVICE_RABBIT_MQ_URI=amqp://user:password@localhost:5672

GATEWAY_PORT=8086
MODUS=service
SERVICE_CLASS=de.unistuttgart.isw.weather.WeatherService

 
