@startuml mainDataModel

class A {
    + modelName: string
    + operator: "GET" | "INSERT" | "UPDATE" | "DELETE"| "FUNCTION"
    + payload: PayloadA
}

class PayloadA {
    selectors: string[]
    where: Map<string, string>
    values: Map<string, string>
    funName: string
    funArgs: Map<string, string>
}

A --> PayloadA: hasPayload

class B {
    + modelName: string
    + operator: "GET" | "INSERT" | "UPDATE" | "DELETE"| "FUNCTION"
    + payload: PayloadB
}

class PayloadB {
    selectors: string[]
    where: Map<string, string>
    values: Map<string, string>
    funName: string
    funArgs: Map<string, string>
}

B --> PayloadB: hasPayload


class C {
    + serviceName: string
    + responseType: "queue" | "callback" | "await"
    + dsl: GatewayDSL;
}


class GatewayRequestResponse {
    type: "json" | "xml" | "html" | "text"
    data: base64string
}

note left of C
    responseType: queue - response will be sent to a queue
    responseType: callback - response will be sent to a callback (Https)
    responseType: await - response will be awaited as immediate response (HTTPs)
end note

@enduml