# list the machines in the MBDO experiment
servers:
  hosts:
    mbdo_server:
      ansible_host: mbdo.irisa.fr
      ansible_user: mbdo-admin
    #  ansible_become_pass: "{{ mbdo_server_become_pass  | default('')}}"

plcs:
  hosts:
    RevPi01: 
      ansible_host: RevPi103156.local 
      ansible_user: pi
    #  ansible_become_pass: "{{ revpi_01_become_pass  | default('')}}"
    RevPi02: 
      ansible_host: RevPi103259.local 
      ansible_user: pi
    #  ansible_become_pass: "{{ revpi_02_become_pass  | default('')}}"
    RevPi03: 
      ansible_host: RevPi103228.local 
      ansible_user: pi
    #  ansible_become_pass: "{{ revpi_03_become_pass  | default('')}}"



  vars:
    # enable jump ansible_host
    # prefer direct connexion whenever possible (using the wifi network) (ie. comment the ProxyCommand line ) 
    ansible_ssh_common_args: -T -A -o ProxyCommand="ssh -W %h:%p -q mbdo-admin@mbdo.inria.fr" -o StrictHostKeyChecking=no



all:
  children:
    servers:
    plcs:
