<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.codewithnk.course</groupId>
    <artifactId>my-project</artifactId>
    <version>1.0</version>



    <dependencies>
    

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.14.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.12</version>
        </dependency>
    </dependencies>
</project>