# MongoDB Configuration


# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=aas_db
spring.data.mongodb.uri=mongodb+srv://peterragy:2la6QFimctSxfbTX@cluster0.dsdtpye.mongodb.net/aas_db?retryWrites=true&w=majority&appName=Cluster0

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=USER

# Increase multipart file size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Tomcat-specific configuration
server.tomcat.max-swallow-size=50MB
basyx.backend = InMemory
spring.jmx.enabled=false

