from enum import Enum


class RequestedParameter(Enum):

    REFERENCESWITCHHORIZONTALAXIS = 1
    LIGHTBARRIERINSIDE = 2
    LIGHTBARRIEROUTSIDE = 3
    REFERENCESWITCHVERTICALAXIS = 4
    HORIZONTALAXISSTEP = 5
    VERTICALAXISSTEP = 6
    REFERENCESWITCHCANTILEVERFRONT = 7
    REFERENCESWITCHCANTILEVERBACK = 8
    MOTORCONVEYORBELTFORWARD = 9
    MOTORCONVEYORBELTBACKWARD = 10
    MOTORVERTICALAXISDOWNWARD = 11
    MOTORVERTICALAXISUPWARD = 12
    MOTORCANTILEVERFORWARD = 13
    MOTORCANTILEVERBACKWARD = 14


    PUSHBUTTONSLIDER1FRONT= 15
    PUSHBUTTONSLIDER1REAR = 16
    PUSHBUTTONSLIDER2FRONT = 17
    PUSHBUTTONSLIDER2REAR = 18
    LIGHTBARRIERSLIDER1 = 19
    LIGHTBARRIERMILLINGMACHINE = 20
    LIGHTBARRIERLOADINGSTATION = 21
    LIGHTBARRIERDRILLINGMACHINE = 22
    LIGHTBARRIERCONVEYORBELTSWAP = 23
    MOTORSLIDER1BACKWARD = 24
    MOTORSLIDER1FORWARD = 25
    MOTORSLIDER2BACKWARD = 26
    MOTORSLIDER2FORWARD = 27
    MOTORCONVEYORBELTFEED = 28
    MOTORCONVEYORBELTMILLINGMACHINE = 29
    MOTORMILLINGMACHINE = 30
    MOTORCONVEYORBELTDRILLINGMACHINE = 31
    MOTORDRILLINGMACHINE = 32
    MOTORCONVEYORBELTSWAP = 33


    REFERENCESWITCHTURNTABLEPOSITIONVACUUM = 34
    REFERENCESWITCHTURNTABLEPOSITIONBELT = 35
    LIGHTBARRIERENDOFCONVEYORBELT = 36
    REFERENCESWITCHTURNTABLEPOSITIONSAW = 37
    REFERENCESWITCHVACUUMPOSITIONTURNTABLE = 38
    REFERENCESWITCHOVENFEEDERINSIDE = 39
    REFERENCESWITCHOVENFEEDEROUTSIDE = 40
    REFERENCESWITCHVACUUMPOSITIONOVEN = 41
    LIGHTBARRIEROVEN = 42
    MOTORTURNTABLECLOCKWISE = 43
    MOTORTURNTABLECOUNTERCLOCKWISE = 44
    MOTORSAW = 45
    MOTOROVENFEEDERRETRACT = 46
    MOTOROVENFEEDEREXTEND = 47
    MOTORVACUUMTOWARDSOVEN = 48
    MOTORVACUUMTOWARDSTURNTABLE = 49
    LIGHTOVEN = 50
    VALVEVACUUM = 51
    VALVELOWERING = 52
    VALVEOVENDOOR = 53
    VALVEFEEDER = 54


    PULSECOUNTER = 55
    LIGHTBARRIERINLET = 56
    LIGHTBARRIERBEHINDCOLORSENSOR = 57
    LIGHTBARRIERWHITE = 58
    LIGHTBARRIERRED = 59
    LIGHTBARRIERBLUE = 60
    MOTORCONVEYORBELT = 61
    COMPRESSOR = 62
    VALVEFIRSTEJECTORWHITE = 63
    VALVESECONDEJECTORRED = 64
    VALVETHIRDEJECTORBLUE = 65


    REFERENCESWITCHROTATE = 66

    ROTATESTEP = 68
    MOTORVERTICALAXISUP = 69
    MOTORVERTICALAXISDOWN = 70
    MOTORHORIZONTALAXISBACKWARD = 71
    MOTORHORIZONTALAXISFORWARD = 72
    MOTORROTATECLOCKWISE = 73
    MOTORROTATECOUNTERCLOCKWISE = 74

    LIGHTBARRIERFEEDSTATION = 75
    LIGHTBARRIERSWAPSTATION = 76

    LIGHTBARRIERGOODSINOUT = 77
    LIGHTBARRIERPUNCHINGMACHINE = 78
    SWITCHPUNCHINGMACHINEUP = 79
    SWITCHPUNCHINGMACHINEDOWN = 80
    MOTORPUNCHINGMACHINEUP = 81
    MOTORPUNCHINGMACHINEDOWN = 82


    REFERNCESWITCHCLAW = 83
    PULSECOUNTERGRIPPER = 84
    REFERENCESWITCHGRIPARM = 85
    PULSECOUNTERGRIPARM = 86
    MOTORGRIPPEROPEN = 87
    MOTORGRIPPERCLOSE = 88
    MOTORGRIPARMFORWARD = 89
    MOTORGRIPARMBACKWARD = 90

    ALL = 91
