@startuml


start
group "Client - Start" {
:OpenClient;

}

group "Client Authentication" {
    :Send Auth Request with RedirectUrl;
    :Redirect to Auth Service;

}

group "Auth Service" {
    :Fetch Auth Methods;
    :Render Auth Service Frontend;
    :Ask User For Credentials;
    :User Enters Credentials;
    if (Credentials Valid) then (yes)
        :Fetch User Roles;
        :Fetch Scopes for Roles;
        :Build Scopes for Token;
        :Generate Token with Scopes;
        :Generate OTP for retrieving Token;
        :Call RedirectUrl with OTP;
    else (no)
        :Fetch Error;
        :Call RedirectUrl with Error;        
    endif;


}

group "Client Authenticated" {
    :FetchOneTimePassword;
    :FetchTokenWithOTP;
    :AddTokenToHeader;
    
}


@enduml