@startuml 

autonumber 1.1
title Authentication Sequence Diagram

participant "Client Frontend" as client_frontend
participant "Service Gateway" as service_gateway
participant "Auth Service" as service_authservice
participant "Service" as service
client_frontend -> service_gateway: Send Request without Token
service_gateway -> service_authservice: Fetch Scopes based on Token
service_authservice --> service_gateway: Return Scopes
service_gateway -> service_gateway: Check if Scopes are valid for the requested service
service_gateway -> service: Run Pre-Flight Check to validate if scopes is sufficient for service endpoint.
service --> service_gateway: Return Pre-Flight Check Result
alt Pre-FlightSuccessful case 
    service_gateway -> service: Forward Request to Service
    service --> service_gateway: Return Result
end
alt status == 401 case 
    service_gateway --> client_frontend: Return 401 Unauthorized
else
    service_gateway --> client_frontend: Return 2xx Status Code
end
autonumber 2.1
alt status == 401 case 
    ' oauth flow here
    client_frontend -> service_gateway: /login?redirect_uri=client_frontend
    service_gateway -> service_authservice: Forward Request to Auth Service
    service_authservice -> service_authservice: Render Auth Service Frontend
    service_authservice -> service_authservice: Ask User For Credentials
    service_authservice -> service_authservice: User Enters Credentials
    service_authservice -> service_authservice: Fetch User Roles
    service_authservice -> service_authservice: Fetch Scopes for Roles
    service_authservice -> service_authservice: Build Scopes for Token
    service_authservice -> service_authservice: Generate Token with Scopes and OTP
    service_authservice --> client_frontend: call redirect_uri with OTP 
    client_frontend -> service_gateway: /token?otp=otp
    service_gateway -> service_authservice: Fetch Token with OTP
    service_authservice -> service_authservice: Delete OTP (prevent replay attacks)
    service_authservice --> client_frontend: Return Token
end



@enduml