@startuml 

participant "DT Admin" as dt_admin
participant "Client Frontend" as client_frontend
participant "Service Gateway" as service_gateway
participant "Auth Service" as service_authservice
participant "Auth Service Frontend" as service_authservice_frontend
participant "Service" as service

autonumber 1.1
title Add Users Sequence Diagram

dt_admin -> client_frontend: Open Client and setup new dt
client_frontend -> client_frontend: Ask for new root password
client_frontend -> service_gateway: Send Auth Service init request
service_gateway -> service_authservice: Init Auth Service
service_authservice --> service_gateway: Return Auth Service init state
service_gateway --> client_frontend: Return Auth Service init state confirmation
client_frontend --> dt_admin: Display confirmation and ask to remember the password

autonumber 2.1

dt_admin -> client_frontend: Want to add new roles and user
client_frontend -> service_gateway: Ask for auth service frontend url
service_gateway -> service_authservice: Fetch Auth Service Frontend URL
service_authservice --> service_gateway: Return Auth Service Frontend URL
service_gateway --> client_frontend: Return Auth Service Frontend URL
client_frontend -> service_authservice_frontend: Redirect to Auth Service Frontend URL
service_authservice_frontend -> service_authservice: Login with root password
service_authservice --> service_authservice_frontend: Login token for root user
service_authservice_frontend -> service_authservice: List all available scopes, roles and users.
service_authservice -> service: Fetch all available scopes for the service
service --> service_authservice: Return all available scopes
service_authservice --> service_authservice_frontend: Return all available scopes, roles and users.
service_authservice_frontend -> service_authservice: Add new roles and users and assign scopes to roles



@enduml